services:
  cyna-auth:
    platform: linux/amd64
    image: registry.gitlab.com/cyna-project/cyna-auth:latest
    container_name: cyna-auth
    ports:
      - "3001:3000"  # host:container
    env_file:
      - ./cyna-auth/.env
    depends_on:
      - postgres-auth

  cyna-product:
    platform: linux/amd64
    image: registry.gitlab.com/cyna-project/cyna-product:latest
    container_name: cyna-product
    ports:
      - "4001:4000"
    env_file:
      - ./cyna-product/.env
    depends_on:
      - postgres-product

  cyna-billing:
    platform: linux/amd64
    image: registry.gitlab.com/cyna-project/cyna-billing:latest
    container_name: cyna-billing
    ports:
      - "5001:5000"
    env_file:
      - ./cyna-billing/.env

  cyna-gateway:
    platform: linux/amd64
    image: registry.gitlab.com/cyna-project/cyna-gateway:latest
    container_name: cyna-gateway
    ports:
      - "2000:2000"
    env_file:
      - ./cyna-gateway/.env

  cyna-app:
    platform: linux/amd64
    image: registry.gitlab.com/cyna-project/cyna-app:latest
    container_name: cyna-app
    ports:
      - "5173:80"
    env_file:
      - ./cyna-app/.env


  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cyna_auth
    ports:
      - "5433:5432"
    volumes:
      - pgdata-auth:/var/lib/postgresql/data

  postgres-product:
    image: postgres:15
    container_name: postgres-product
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cyna_product
    ports:
      - "5434:5432"
    volumes:
      - pgdata-product:/var/lib/postgresql/data

volumes:
  pgdata-auth:
  pgdata-product: